### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by willer94** [RoyalVane/CLAN#22]
Hi, I trained the model on a 1080Ti, but get CUDA out of memory error. 
```
python  CLAN_train.py --snapshot-dir ./snapshots/GTA2Cityscapes
....
Traceback (most recent call last):
  File "CLAN_train.py", line 426, in <module>
    main()
  File "CLAN_train.py", line 319, in main
    loss_seg = (loss_calc(pred_source1, labels_s, args.gpu) + loss_calc(pred_source2, labels_s, args.gpu))
  File "CLAN_train.py", line 165, in loss_calc
    return criterion(pred, label)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/ubuntu/76c3afb9-9877-4540-ac95-6a70ac97a8fc/PycharmProjects/UDASS/CLAN/utils/loss.py", line 72, in forward
    predict = P[target_mask.view(N, 1, H, W).repeat(1, C, 1, 1)].view(C, -1)
RuntimeError: CUDA error: out of memory
```
The sizes of GTA5 images and Cityscapes images are set as default in the code.
So 11G memory is not enough?

**Comment by willer94** [comment]
I set the GTA image size to 512x1024, as said in the paper, and there is no error.
